[sh,zsh] always load dots settings

diff --git a/sh/shrc b/sh/shrc
--- a/sh/shrc
+++ b/sh/shrc
@@ -5,9 +5,20 @@
 #
 
 
-# .-----------------------------.
-# | Check machine dependent env |
-# '-----------------------------'
+# .----------------------------.
+# | Load machine dependent env |
+# '----------------------------'
+
+if [ -z "$DOTSENV" ]; then
+    source "$HOME/.dots"
+else
+    source "$DOTSENV"
+fi
+
+if [ "$?" -ne "0" ]; then
+    echo '[FATAL] Unable to load $HOME/.dots' >&2
+    return 255
+fi
 
 if [ -z "$DOTS" ] || [ -z "$DOTSLO" ]; then
     echo '[FATAL] $DOTS or $DOTSLO is not defined, please set them in $HOME/.dots' >&2
